### ISSUE TITLE
pull requests官方解释

### ISSUE THREAD

**Issue by Hakuin123** [Mimangz/SEC-REC#8]
看到mmz之前测试过pull requests功能但是不太清楚是干什么用的
以下是官方解释，手打翻译

Eddie不是唯一一个使用L700拖拉机的
全世界其他的拖拉机正在收集水分数据
他们需要继续保持平稳运行，即便Vijay正在添加新的功能
他需要一个专用的实验场地
他所做的改变不会在完成之前影响到农场
所以他通过代码创造了另一个时间线
在那里他可以安全地改变软件
现在他已经准备好了开始写新的软件
GitHub记录Vijay变动并保存他进展的快照
当他已经准备好和他的团队对接
他会在GitHub发起一个“Pull”的请求
Pull请求会使得其他人看到你所提出的改变
他们可以回顾并讨论
这意味着Vijay的团队可以帮助解决其中的困难
或者直接去改进
在GitHub上，每个人都有一个项目的备份
所以如果Melinda有一个想法，可以使Vijay的工作更好
她可以在自己的拷贝中添加
在Pull请求中，GitHub记录着每个人的工作和反馈
并在旁边展示着来自团队其他人的相关信息
一旦团队觉得赞同这个改变
Vijay就可以将新的代码整合进项目中
一旦他整合了进去，所有人都可以看到新的功能

来源：https://www.youtube.com/watch?v=w3jLJU7DT5E

**Comment by Mimangz** [comment]
可以，这个解释很不错（）
